---
deployment:
  tasks:
    - export DEPLOYPATH=/home/resqyjgn/
    - /bin/cp -r * $DEPLOYPATH #copy all from root on first deploy
  #  - /bin/cp -r ./app/* $DEPLOYPATH/app
  #  - /bin/cp -r ./config/* $DEPLOYPATH/config
  #  - /bin/cp -r ./database/* $DEPLOYPATH/database
  #  - /bin/cp -r ./resources/* $DEPLOYPATH/resources
 #   - /bin/cp -r ./routes/* $DEPLOYPATH/routes
  #  - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/js
  #  - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/css


  #  - /bin/cp /<sub_folder>/<file_name> $DEPLOYPATH #copy specific file from source sub folder
  #  - /bin/cp <file_name> $DEPLOYPATH #Copy specific file to destination from root
#  - /bin cp /<sub_folder>/* $DEPLOYPATH #copy all from sub folder root